version: "3.5"

networks:
  proxy:
    name: proxy

services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: always
    hostname: unifi
    depends_on:
      - traefik
    environment:
      JAVA_OPTS: -Xmx512M
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"
    volumes: ["../data/unifi/:/config"]
    networks:
      - proxy
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.services.unifi.loadbalancer.server.port=8080
      - traefik.http.routers.unifi.rule=Host(`unifi.pi.soniqua`)
      - traefik.https.routers.unifi.loadbalancer.server.port=8443
      - traefik.https.routers.unifi.rule=Host(`unifi.pi.soniqua`)

#  pihole:
#    image: pihole/pihole:latest
#    container_name: pihole
#    restart: always
#    dns:
#      - 127.0.0.1
#      - 1.1.1.1
#    cap_add:
#      - NET_ADMIN
#    hostname: pihole
#    ports:
#      - '53:53'
#      - '67:67'
#      - '8000:80'
#    environment:
#      TZ: "UTC"
#      ServerIP: "10.1.1.2"
#    volumes:
#      - '/etc-pihole/:/etc/pihole/'
#      - '/etc-dnsmasq.d:/etc/dnsmasq.d'
#    labels:
#      - "traefik.enabled=true"
#      - "traefik.protocol=http"
#      - "traefik.port=8000"
#      - "traefik.frontend.rule=Host:pihole.pi.soniqua"
#      - "traefik.frontend.passHostHeader=true"
 
  traefik:
    restart: always
    image: "traefik"
    container_name: "traefik"
    #command: --api.insecure=true --providers.docker=true --providers.docker.exposedbydefault=false --providers.docker.network=proxy --defaultentrypoints=https,http --entryPoints=Name:https Address ::443 TLS
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
    networks:
      - proxy
