version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #network_mode: host
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      TZ: "UTC"
      ServerIP: "10.1.1.2"
      VIRTUAL_HOST: "pihole.pi.soniqua"
      DNSMASQ_LISTENING: all
    volumes:
      - '/etc-pihole/:/etc/pihole/'
      - '/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    depends_on:
     - dhcphelper
    networks:
      internal:
        ipv4_address: '172.32.0.100'
      proxy: {}

  dhcphelper:
    build: ./dhcp-helper
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.32.0.100
    cap_add:
     - NET_ADMIN

networks:
  internal:
    ipam:
      config:
        - subnet: 172.32.0.0/24
  proxy:
    external: true
